
on:
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login
        uses: azure/login@v3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Verify Login
        run: az account show

      - name: Terraform installer
        uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: "1.14.6"
      - run: |
          terraform init \
            -backend-config="resource_group_name=rg-github" \
            -backend-config="storage_account_name=githubpipeline" \
            -backend-config="container_name=gittfstate" \
            -backend-config="key=prod.tfstate"

      - run: terraform plan
      - run: terraform apply -auto-approve
      
